In [1]:
import numpy as np

In [2]:
#1.將下列清單(list1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")
array1 = np.array(range(30))

In [3]:
print (array1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [4]:
ans1 = np.reshape(array1, (5,6))

In [5]:
print (ans1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [ ]:
#2.呈上題的array，找出被6除餘1的數的索引

In [6]:
np.where(ans1%5==1)

(array([0, 1, 1, 2, 3, 4], dtype=int64),
 array([1, 0, 5, 4, 3, 2], dtype=int64))