In [1]:
import numpy as np
from io import StringIO

In [2]:
#. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])

In [3]:
with open('array3.npz', 'wb') as f:
    np.savez(f, array1, array2)

In [4]:
npzfile = np.load('array3.npz')

In [6]:
npzfile.files

['arr_0', 'arr_1']

In [9]:
print(npzfile)

In [10]:
print(npzfile['arr_0'])
print(npzfile['arr_1'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [ ]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔

In [11]:
print(npzfile['arr_0'])
print(npzfile['arr_1'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]


In [12]:
array3 = np.arange(10)

In [13]:
answer1 = np.load('array3.npz')

In [20]:
print( answer1)

In [21]:
print(answer1['arr_0'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [23]:
with open('trible_array.npz', 'wb') as f:
    np.savez(f, answer1['arr_0'], answer1['arr_1'], array3)

In [29]:
answer2 = np.load('trible_array.npz')

In [30]:
print(answer2['arr_0'])
print(answer2['arr_1'])
print(answer2['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[0 1 2 3 4 5 6 7 8 9]
